version: '2'
services:
    eventq-app:
        image: eventq
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://eventq-mysql:3306/eventq?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    eventq-mysql:
        extends:
            file: mysql.yml
            service: eventq-mysql
